### ISSUE TITLE
Init with formValues

### ISSUE THREAD

**Issue by Themesaul** [openfext/vue-form-builder#10]
When I pass in v-model formValues with values the library empties them. I would like to be able to pass formValues with data. I have used the input event to make this mechanism, but I think the library should admit it.

**Comment by felixpy** [comment]
Sorry for late response, can you provide some example code?

**Comment by Zeppelinsaikou** [comment]
`export default {
  name: 'ElFormBuilder',

  props: {
    model: {
      type: Object,
      default () {
        return {}
      }
    },
 ...
`
这里应该使用**value**字段接收而不是**model**，v-model指令的默认接受字段是value。
所以因为一直接收不到默认值，就会清空用户传入的默认值。
