### ISSUE TITLE
Which files do I modify to turn it into the demo?

### ISSUE THREAD

**Issue by nbilbeny** [openfext/vue-form-builder#6]
Hi,

I ran the commands on terminal but I don't know which changes to make to which files to make it look like the live demo. Help greatly appreciated.

The project is running correctly on localhost with a login form but I don't know how to go from there to having the larger form from the example and the file to be edited to enable form changes.

**Comment by felixpy** [comment]
Sorry for late response, take a look at this file in the sample project:

https://github.com/codetrial/element-form-builder/blob/develop/examples/simple-demo/src/components/FormBuilderPreview.vue
