### ISSUE TITLE
Problem when updating parent data

### ISSUE THREAD

**Issue by codanux** [openfext/vue-form-builder#8]
I encountered with an issue while updating parent data here:

https://github.com/codetrial/element-form-builder/blob/22916aa8d4074998c21533b9c9b79a8305512e7d/src/formbuilder.js#L41

Here is a quick fix I applied

```
watch: {
    formValues: {
      handler: function handler(formValues) {
        this.updating = true;
        this.$emit('update:model', formValues); // model props update
      },
      deep: true
    },
}

```

I can send a PR if needed.

Regards

**Comment by felixpy** [comment]
Sorry for late response, maybe using v-model can solve this problem?

https://github.com/codetrial/element-form-builder/blob/17e44f1c1373fa01cb16d5f07bce68601d310184/examples/simple-demo/src/components/FormBuilderPreview.vue#L12

Refer to this feature of Vue.js:

https://vuejs.org/v2/guide/components.html#Using-v-model-on-Components
